# Generated by Django 4.1.1 on 2023-05-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
